#!/bin/bash
#
#  Copyright (c) 2021, RedNodeLabs.
#  All rights reserved.
#

# shellcheck source=script/_initrc
. "$(dirname "$0")"/_initrc
. script/_border_routing
. script/_otbr
. script/_ipforward
. script/_nat64
. script/_dns64
. script/_dhcpv6_pd
. script/_network_manager
. script/_rt_tables
. script/_swapfile
. script/_sudo_extend
. script/_disable_services

main()
{
    . "$BEFORE_HOOK"
    extend_sudo_timeout
    setup_swapfile
    disable_services
    otbr_uninstall
    border_routing_uninstall
    network_manager_uninstall
    dhcpv6_pd_uninstall
    nat64_uninstall
    dns64_uninstall
    rt_tables_uninstall
    ipforward_uninstall

    #ipforward_install
    #rt_tables_install
    #nat64_install
    #dns64_install
    #network_manager_install
    #dhcpv6_pd_install
    #border_routing_install
    #otbr_install
    otbr_build
    . "$AFTER_HOOK"
}

main
